name: EVE Market Data Pipeline

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes for current orders
    - cron: '0 6 * * 1'     # 6 AM every Monday for historical data
  workflow_dispatch:        # Manual trigger option

jobs:
  process_market_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Fetch and process current market orders
        run: python scripts/fetch_current_orders.py

      - name: Cache current orders
        uses: actions/cache@v3
        with:
          path: data/raw/current_orders.csv
          key: ${{ runner.os }}-market-orders-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-market-orders-
      
      - name: Cache historical data
        uses: actions/cache@v3
        with:
          path: |
            data/raw/historic_prices.csv
            data/raw/historic_volumes.csv
          key: ${{ runner.os }}-historic-data-${{ github.run_number }}-${{ github.run_attempt }}
          restore-keys: |
            ${{ runner.os }}-historic-data-
      
      - name: Process historical data (Mondays only)
        if: github.event.schedule == '0 6 * * 1' || github.event_name == 'workflow_dispatch'
        run: python scripts/fetch_historic_data.py
      
      - name: Generate trade pairs analysis
        run: python scripts/generate_trade_pairs.py
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/processed/trade_analysis.csv
          git diff --staged --quiet || git commit -m "Update trade analysis data [skip ci]"
          git push
